# Recipe for training a GRPO model on an A100 GPU

# Dataset
dataset_name: "jimbowyer123/countdown"
split: "train"
system_prompt: "You are a reasoning agent. You will be given a problem to solve.\n\nYou should think about the problem before you give an answer.\n\nEnclose your thoughts within the <think> </think> tags and provide your answer within the <answer> </answer> tags.\n\nThe complete format of your response should be:\n\n<think>\n...\n</think>\n<answer>\n...\n</answer>"

# Base Model
model_name: "unsloth/Qwen2.5-7B"
max_seq_len: 2048
load_in_4bit: true
fast_inference: true
gpu_memory_utilization: 0.5

# Peft Model
lora_rank: 32
target_modules:
  - "q_proj"
  - "k_proj"
  - "v_proj"
  - "o_proj"
  - "gate_proj"
  - "up_proj"
  - "down_proj"
lora_alpha: 32
use_gradient_checkpointing: "unsloth"
random_state: 42
use_dora: false

# Training Args
beta: 0.01
use_vllm: true
per_device_train_batch_size: 1
num_generations: 16
gradient_accumulation_steps: 4
learning_rate: 2.5e-7
adam_beta1: 0.9
adam_beta2: 0.999
warmup_steps: 100
lr_scheduler_type: cosine
optim: "paged_adamw_8bit"
logging_steps: 1
bf16: true
fp16: false
max_prompt_length: 256
max_completion_length: 1024
max_steps: -1
num_train_epochs: 1
max_grad_norm: 0.1
output_dir: "unsloth_grpo"
overwrite_output_dir: true
report_to:
  - "wandb"
seed: 42
save_steps: 50
save_total_limit: 1
hub_model_id: "jimbowyer123/OtterCountdown"
push_to_hub: true
log_completions: true




