# Model arguments
model_name_or_path: Qwen/Qwen2.5-3B-Instruct
model_revision: main
torch_dtype: bfloat16

# Data training arguments
dataset_name: jimbowyer123/countdown

# Num processes is less by 1 as vLLM is using 1 GPU
num_processes: 7

# GRPO trainer config
bf16: true
use_vllm: true
vllm_device: auto
vllm_gpu_memory_utilization: 0.7
do_eval: false
gradient_accumulation_steps: 16
hub_model_id: jimbowyer123/OtterCountdown
hub_strategy: every_save
learning_rate: 1.0e-05
log_level: info
logging_steps: 10
logging_strategy: steps
lr_scheduler_type: cosine
max_prompt_length: 512
max_completion_length: 4096
max_steps: -1
num_train_epochs: 1
output_dir: OtterCountdown
overwrite_output_dir: true
per_device_train_batch_size: 1
save_strategy: steps
save_steps: 250
save_total_limit: 1
push_to_hub: true
report_to:
- wandb
seed: 42
warmup_ratio: 0.1
num_generations: 8
