# Model arguments
model_name_or_path: Qwen/Qwen2.5-7B-Instruct
model_revision: main
torch_dtype: bfloat16
load_in_8bit: true
attn_implementation: flash_attention_2
use_peft: true
lora_r: 32
lora_alpha: 32
lora_target_modules: ["q_proj", "v_proj"]
lora_dropout: 0.0

# Data training arguments
dataset_name: jimbowyer123/countdown

# GRPO trainer config
bf16: true
use_vllm: false
vllm_device: auto
vllm_gpu_memory_utilization: 0.7
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
do_eval: true
eval_steps: 100
gradient_accumulation_steps: 2
hub_model_id: jimbowyer123/OtterCountdown
hub_strategy: every_save
learning_rate: 1.0e-05
log_level: info
logging_steps: 5
logging_strategy: steps
lr_scheduler_type: cosine
max_prompt_length: 512
max_completion_length: 1024
max_steps: -1
num_train_epochs: 1
output_dir: OtterCountdown
overwrite_output_dir: true
per_device_train_batch_size: 1
per_device_eval_batch_size: 8
save_strategy: steps
save_steps: 250
save_total_limit: 1
push_to_hub: true
report_to:
- wandb
seed: 42
warmup_ratio: 0.0
num_generations: 8
